### ISSUE TITLE
Unicode issue

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/win-wallpaper#1]
Lets say we have an image called `få.jpg`. Running `wallpaper få.jpg` correctly sets the desktop wallpaper to that image, but when doing `wallpaper` afterwards to get the path back the encoding is corrupted:

```
C:\Users\sindresorhus\Desktop\f�.jpg
```

My C skills are noobish at best and would really appreciate some guidance on this :)

-

Compiled with GCC on Windows 8.1.

**Comment by passy** [comment]
Never had the displeasure of having to work with the win32 API, but I think you want to use `WCHAR` instead of a plain `char[]` for storing the result based on what I've seen in other places.

**Comment by pornel** [comment]
AFAIK [Windows doesn't speak UTF-8](http://simonsapin.github.io/wtf-8/) and its filenames are in UCS-2 or UTF-16.

Therefore any API that is compatible with 8-bit C strings will have to fall back to Windows' ANSI codepage and give you names lossily-converted to some crappy legacy encoding (which encoding depends on Windows language and settings).

1. Don't use standard Win32 functions, look for their "wide" equivalents.
2. Don't use C stdlib (`puts(imagePath)` won't work with `wchar`).

**Comment by GianlucaGuarini** [comment]
Here you can see how to use UTF-8 encoding on any platform http://utf8everywhere.org/#how unfortunately I cannot test your code on a windows platform but I do not think it's that hard

**Comment by wbond** [comment]
I think there are a few things going on here. I'm not an expert with the Windows API, but I have done a bit of interfacing with it via FFI bindings in a few languages.

As previous commenters have noted, the Windows API functions are available in ANSI (single-byte) and Unicode variations. If a function accepts or returns strings, there will be two variations: `FunctionNameA` and `FunctionNameW`. The `W` version will accept and return wide char strings, which are UTF-16. The `A` version accepts ANSI strings, depending on the code page the system is configured to. Depending on whether or not you compile your program with `UNICODE` defined, the `W` or `A` version will be aliased to the non-suffixed name. See https://msdn.microsoft.com/en-us/library/ff381407.aspx for more general info.

Now, what is interesting is that the code is clearly working with the character `å` when setting the filename. This indicates to me that your system codepage includes this character. If you are using English on your Windows install, you are most likely running [Windows 1252](http://en.wikipedia.org/wiki/Windows-1252). The `å` character corresponds to byte `\xE5`.

From this, I think we can determine that it is not because you aren't using wide chars (Unicode) that it is failing. Rather, I think it is likely depending on what terminal emulator you are using that it does not know how to interpret the byte `\xE5` being printed by your program.

There are functions to deal with getting and setting the console codepage. [GetConsoleOutputCP](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683169(v=vs.85).aspx) and [SetConsoleOutputCP](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686036(v=vs.85).aspx). Now, there are a whole bunch of code pages (http://en.wikipedia.org/wiki/Windows_code_page), but while Windows doesn't support UTF-8 within function calls, it does have a codepage of 65001 that represents UTF-8 output to the console.

So it might be interesting to run the `chcp.exe` CLI app to see what codepage you are using. Then you could probably either change it to match the system codepage (which is what the result of `SystemParametersInfoA()` would be), or use `SystemParametersInfoW()` with wide chars, set the codepage to 65001 and use [WideCharToMultiByte](https://msdn.microsoft.com/en-us/library/windows/desktop/dd374130(v=vs.85).aspx).

Anyway, hope this helps some.

**Comment by Qix-** [comment]
Because you're using the ANSI versions of the functions, silly! :dancer: 

In the windows API, almost every function call that works with text is actually a macro definition. It's pretty much the following:

```c
#ifdef UNICODE
#define MessageBox MessageBoxA
#else
#define MessageBox MessageBoxW
#endif
```

for `A`scii and `W`ide, respectively. You could `-DUNICODE` if you wanted, or just use the Wide version (the preprocessor definition doesn't govern whether or not the multibyte definitions exist; it just affects the macros).

---

Why? Because Windows uses wide characters (their own weird version of UTF-16). For that, use the type `wchar_t` instead of char.

Here is how to fix this (my windows box is being a pain so I'll leave it up to you, sorry!):

- [L28](https://github.com/sindresorhus/win-wallpaper/blob/master/wallpaper.c#L28): `char` -> `wchar_t`
- [L30](https://github.com/sindresorhus/win-wallpaper/blob/master/wallpaper.c#L30): `SystemParametersInfo` -> `SystemParametersInfoW`
- [L31](https://github.com/sindresorhus/win-wallpaper/blob/master/wallpaper.c#L31):

```c
puts(imagePath);
```

to 

```c
DWORD written;
WriteConsoleW(GetStdHandle(STD_OUTPUT_HANDLE), &imagePath[0], wcslen(&imagePath[0]), &written, 0);
```

The above line first gets the stdout handle (all console buffers have handled, similar to `FILE*` on unix systems), then it gets the wide character length of the string, then passes all of them stuff to `WriteConsoleW`, which writes multibyte text to the console.

---

Give that a shot; I recommend porting all of the code over to unicode, and since this is a windows only program you should use `wmain(int, wchar_t**)` instead of `main(int, char**)` so you can avoid conversions!
